application:
  name: simple-example-node
  project: simple-example-node
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: simple-example-node
    paths:
    - /*
